//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Quantity { get; set; }
        public string Brand { get; set; }
        public string Unitprice { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<int> IsSale { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
